spring:
  application:
    name: minesweeper-api

  r2dbc:
    url: ${SPRING_R2DBC_URL:r2dbc:postgresql://localhost:5432/minesweeper}
    username: ${SPRING_R2DBC_USERNAME:postgres}
    password: ${SPRING_R2DBC_PASSWORD:password}

  flyway:
    enabled: true
    url: ${SPRING_FLYWAY_URL:jdbc:postgresql://localhost:5432/minesweeper}
    user: ${SPRING_FLYWAY_USER:postgres}
    password: ${SPRING_FLYWAY_PASSWORD:password}
    baseline-on-migrate: true
    validate-on-migrate: false

server:
  port: ${SERVER_PORT:8080}
  ssl:
    enabled: true
    key-store: classpath:/jks/keystore.p12
    key-store-password: ${SSL_KEY_STORE_PASSWORD:changeit}
    key-store-type: PKCS12
    key-alias: ${SSL_KEY_ALIAS:mycert}

logging:
  level:
    root: INFO
    org.springframework.r2dbc: DEBUG
    org.springframework.flyway: DEBUG
